export const USERS_STATISTICS_SUCCESS = 'USERS_STATISTICS_SUCCESS',
      USERS_STATISTICS_FAIL = 'USERS_STATISTICS_FAIL',
      USERS_STATISTICS_REQUEST = 'USERS_STATISTICS_REQUEST',
      SELECT_USER = 'SELECT_USER'
